micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    #    h2
    #    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    #    driverClassName: org.h2.Driver
    #    username: sa
    #    password: ''
    #    schema-generate: CREATE_DROP
    #    dialect: H2

    url: ${$POSTGRES_URL:`jdbc:postgresql://localhost:5432/casa-do-codigo`}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:`postgres`}
    password: ${POSTGRES_PASSWORD:`password`}
    schema: cdc
#    schema-generate: CREATE_DROP
#    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hb2ddl:
          auto: update

