micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    #    url: ${$POSTGRES_URL:`jdbc:postgresql://localhost:5432/casa-do-codigo`}
    url: jdbc:postgresql://localhost:5432/casa-do-codigo
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:`postgres`}
    password: ${POSTGRES_PASSWORD:`password`}
    schema: cdc
    schema-generate: CREATE_DROP
#    dialect: H2

#jpa.default.properties.hibernate.hbm2ddl.auto: update

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

# api externa
url-service-cep: https://brasilapi.com.br/api/cep/v1